[build]
  command = "pnpm build"
  publish = "public"

[dev]
  command = "pnpm dev"
  port = 3001
  targetPort = 3001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"
